SELECT DELIVERY_ORDER.ORDER_ID,
       STORE_NAME,
       STORE_ADDRESS.STREET,
       RECIPIENT.ORDER_ID,
       LAST_NAME,
       FIRST_NAME,
       RECIPIENT.STREET,
       HOUSE_NUMBER,
       RECIPIENT.ZIP,
       CUSTOM_DROPPOFF_PLACE
FROM RECIPIENT,
     DELIVERY_ORDER,
     STORE,
     STORE_ADDRESS
WHERE RECIPIENT.ORDER_ID = DELIVERY_ORDER.ORDER_ID
  AND STORE.STORE_ID = DELIVERY_ORDER.STORE_ID
  AND STORE_ADDRESS.STORE_ID = STORE.STORE_ID
GROUP BY LAST_NAME;
