CREATE OR REPLACE DATABASE LINGENLIEFERT;

USE LINGENLIEFERT;

CREATE OR REPLACE TABLE STORE
(
    STORE_ID   INT,
    STORE_NAME VARCHAR(255) NOT NULL,
    PASSWORD INT CHECK( PASSWORD > 0),
    LOGO       VARCHAR(255),
    PHONE_NR   LONG         NOT NULL,

    PRIMARY KEY (STORE_ID)
);

CREATE OR REPLACE TABLE STORE_ADDRESS
(
    STORE_ID INT,
    STREET   VARCHAR(255) NOT NULL,
    HR_NR    INT          NOT NULL,
    ZIP      INT          NOT NULL,
    PRIMARY KEY (STORE_ID)

);

CREATE OR REPLACE TABLE COORDINATES
(
    STORE_ID  INT,
    LONGITUDE DOUBLE NOT NULL,
    LATITUDE  DOUBLE NOT NULL,
    PRIMARY KEY (STORE_ID)
);

CREATE OR REPLACE TABLE CITY
(
    ZIP       INT,
    CITY_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ZIP)
);

INSERT INTO CITY
VALUES (49808, 'LINGEN');
INSERT INTO CITY
VALUES (49809, 'LINGEN');
INSERT INTO CITY
VALUES (49811, 'LINGEN');

INSERT INTO STORE
VALUES (123456789, 'WILLENBROCK', 'TEST', 017658813328);
INSERT INTO STORE
VALUES (111122222, 'WELT LADEN', 'TEST', 017658813322);

INSERT INTO COORDINATES
VALUES (123456789, 7.318337, 52.518285);

INSERT INTO STORE_ADDRESS
VALUES (123456789, 'BERD-ROSEMEYER_STRASSE', 40, 49809);

SELECT STORE_NAME, STREET, HR_NR, STORE_ADDRESS.ZIP, CITY_NAME
FROM STORE_ADDRESS,
     STORE,
     CITY
WHERE CITY.ZIP = STORE_ADDRESS.ZIP
  AND STORE.STORE_ID = STORE_ADDRESS.STORE_ID;