USE LINGENLIEFERT;

CREATE OR REPLACE TABLE DELIVERY_ORDER
(
    ORDER_ID              INT,
    TIMESTAMP             VARCHAR(255) NOT NULL,
    EMPLOYEE_NAME         VARCHAR(255) NOT NULL,
    PACKAGE_SIZE          ENUM ('S','M','L','XL','XXL'),
    DELIVERYDATE          VARCHAR(255),
    CUSTOM_DROPPOFF_PLACE VARCHAR(255),
    STORE_ID              LONG,
    PRIMARY KEY (ORDER_ID)
);
CREATE OR REPLACE TABLE HANDLINGINFO
(
    ORDER_ID     INT,
    HANDLINGINFO ENUM ('ZEBERECHLICH','SCHWER','GLAS','FLÜSSIGKEIT','GEFAHRGUT'),
    PRIMARY KEY (ORDER_ID, HANDLINGINFO)
);

CREATE OR REPLACE TABLE RECIPIENT
(
    ORDER_ID     INT,
    FIRST_NAME   VARCHAR(255) NOT NULL,
    LAST_NAME    VARCHAR(255) NOT NULL,
    STREET       VARCHAR(255) NOT NULL,
    HOUSE_NUMBER VARCHAR(255) NOT NULL,
    ZIP          INT          NOT NULL,
    PRIMARY KEY (ORDER_ID)
);


