USE LINGENLIEFERT;

CREATE OR REPLACE TABLE DELIVERY_ORDER
(
    ORDER_ID              INT,
    TIMESTAMP             VARCHAR(255) NOT NULL,
    EMPLOYEE_NAME         VARCHAR(255) NOT NULL,
    PACKAGE_SIZE          ENUM ('S','M','L','XL','XXL'),
    DELIVERYDATE          VARCHAR(255),
    CUSTOM_DROPPOFF_PLACE VARCHAR(255),
    STORE_ID              LONG,
    PRIMARY KEY (ORDER_ID)
);
CREATE OR REPLACE TABLE HANDLINGINFO
(
    ORDER_ID     INT,
    HANDLINGINFO ENUM ('ZEBERECHLICH','SCHWER','GLAS','FLÜSSIGKEIT','GEFAHRGUT'),
    PRIMARY KEY (ORDER_ID, HANDLINGINFO)
);

CREATE OR REPLACE TABLE RECIPIENT
(
    ORDER_ID     INT,
    FIRST_NAME   VARCHAR(255) NOT NULL,
    LAST_NAME    VARCHAR(255) NOT NULL,
    STREET       VARCHAR(255) NOT NULL,
    HOUSE_NUMBER VARCHAR(255) NOT NULL,
    ZIP          INT          NOT NULL,
    PRIMARY KEY (ORDER_ID)
);

INSERT INTO DELIVERY_ORDER
VALUES (1, '20.03.2023', 'HENDRIK WILLENBROCK', 'M', '21.01.2023', 'HINTER DEM BUSCH BITTE', 123456789);
INSERT INTO DELIVERY_ORDER
VALUES (2, '19.03.2023', 'HENDRIK WILLENBROCK', 'XXL', '20.01.2023', 'IM KABUFF', 123456789);

INSERT INTO HANDLINGINFO
VALUES (1, 'GLAS');
INSERT INTO HANDLINGINFO
VALUES (1, 'GEFAHRGUT');

INSERT INTO HANDLINGINFO
VALUES (2, 'ZEBERECHLICH');

INSERT INTO RECIPIENT
VALUES (1, 'AMIRALI', 'LAJEVARDI', 'BRÜMMERS WIESE', 23, 49808);
INSERT INTO RECIPIENT
VALUES (2, 'JAN', 'DETTLER', 'BAHNHOFSTR.', '12B', 49809);


SELECT DELIVERY_ORDER.ORDER_ID,
       STORE_NAME,
       STORE_ADDRESS.STREET,
       RECIPIENT.ORDER_ID,
       LAST_NAME,
       FIRST_NAME,
       RECIPIENT.STREET,
       HOUSE_NUMBER,
       RECIPIENT.ZIP,
       CUSTOM_DROPPOFF_PLACE
FROM RECIPIENT,
     DELIVERY_ORDER,
     STORE,
     STORE_ADDRESS
WHERE RECIPIENT.ORDER_ID = DELIVERY_ORDER.ORDER_ID
  AND STORE.STORE_ID = DELIVERY_ORDER.STORE_ID
  AND STORE_ADDRESS.STORE_ID = STORE.STORE_ID
GROUP BY LAST_NAME;


